# Dependencies
markdown:         redcarpet
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            unframework
tagline:          'Personal website of Nick Matantsev'
description:      'Personal website of Nick Matantsev'
url:              http://unframework.com
baseurl:          /

host:             0.0.0.0

author:
  name:           'Nick Matantsev'
  url:            https://twitter.com/unframework

paginate:         5
